spring:
  application.name: kopring-abc
  output.ansi.enabled: always
  h2.console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo;MODE=MYSQL
    username: sa
    password:
  jpa:
    database: h2
    properties:
      hibernate.format_sql: true
    hibernate.ddl-auto: none
  sql:
    init:
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
